volumes:
  web-persist-volume:

services:
  data_service:
    build:
      context: .
      dockerfile: data.dockerfile
    image: data-service:latest
    container_name: data-service-container
    ports:
      - "8081:8081"
    environment:
      - DATA_PORT=8081
      - OPENAI_KEY=${OPENAI_KEY}
  web_service:
    build:
      context: .
      dockerfile: web.dockerfile
    image: web-service:latest
    container_name: web-service-container
    ports:
      - "8080:8080"
    environment:
      - WEB_PORT=8080
      - DATA_PORT=8081
      - WEB_PERSIST_PATH=/web-data
    volumes:
      - web-persist-volume:/web-data
