services:
  import_service:
    build:
      context: .
      dockerfile: import.dockerfile
    image: import-service:latest
    container_name: import-service-container
    ports:
      - "8081:8081"
    environment:
      - IMPORT_PORT=8081
      - OPENAI_KEY=${OPENAI_KEY}
  web_service:
    build:
      context: .
      dockerfile: web.dockerfile
    image: web-service:latest
    container_name: web-service-container
    ports:
      - "8080:8080"
    environment:
      - WEB_PORT=8080
      - IMPORT_PORT=8081
