volumes:
  data-persist-volume:
    driver: local
    driver_opts:
      type: none
      device: ./mounted_data
      o: bind

services:
  data_service:
    build:
      context: .
      dockerfile: data.dockerfile
    image: data-service:latest
    container_name: data-service-container
    ports:
      - "8081:8081"
    environment:
      - DATA_PORT=8081
      - OPENAI_KEY=${OPENAI_KEY}
      - DATA_PERSIST_PATH=/data-persist
    volumes:
      - data-persist-volume:/data-persist
  web_service:
    build:
      context: .
      dockerfile: web.dockerfile
    image: web-service:latest
    container_name: web-service-container
    ports:
      - "8080:8080"
    environment:
      - WEB_PORT=8080
      - DATA_PORT=8081
